apiVersion: v1
kind: Namespace
metadata:
  name: lab4
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: lab4-quota
  namespace: lab4
spec:
  hard:
    requests.cpu: "1000m"
    requests.memory: "1Gi"

